// src/components/tools/CoinCounter.tsx

import { html } from 'htm/preact';
import { useState, useMemo, useEffect } from 'preact/hooks';
import { currencies as defaultCurrencies } from '../../constants/currencies';
import type { Currency, Denomination } from '../../constants/currencies';
import { icons } from '../../constants/icons';
import * as api from '../../utils/api';

const DenominationCard = ({ denomination, count, onCountChange, currencySymbol }) => {
    const subTotal = (count || 0) * denomination.value;

    const handleInputChange = (e) => {
        const val = parseInt(e.currentTarget.value, 10);
        onCountChange(denomination.label, isNaN(val) || val < 0 ? 0 : val);
    };

    return html`
        <div class="denomination-card">
            <div class="denomination-info">
                <strong>${denomination.label}</strong>
                <span class=${denomination.type}>${denomination.type}</span>
            </div>
            <div class="denomination-controls">
                <label for=${`count-${denomination.label}`}>Count:</label>
                <input 
                    id=${`count-${denomination.label}`}
                    type="number" 
                    min="0"
                    value=${count || ''}
                    onInput=${handleInputChange}
                    placeholder="0"
                />
            </div>
            <div class="denomination-subtotal">
                Value: ${subTotal.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${currencySymbol}
            </div>
        </div>
    `;
};

export const CoinCounter = () => {
    const [currencies, setCurrencies] = useState<Currency[]>(defaultCurrencies);
    const [activeCurrencyCode, setActiveCurrencyCode] = useState<Currency['code']>('EUR');
    const [counts, setCounts] = useState<Record<string, number>>({});

    // Load currencies from DB
    useEffect(() => {
        api.fetchCurrencies().then(dbCurrencies => {
            if (dbCurrencies && dbCurrencies.length > 0) {
                const mapped: Currency[] = dbCurrencies.map((c: any) => ({
                    code: c.code,
                    symbol: c.symbol,
                    denominations: (c.denominations || []).map((d: any) => ({
                        value: parseFloat(d.value),
                        type: d.type as 'coin' | 'banknote',
                        label: d.label,
                    })),
                }));
                setCurrencies(mapped);
            }
        }).catch(err => console.error('Failed to load currencies:', err));
    }, []);

    const handleCurrencyChange = (code: Currency['code']) => {
        setActiveCurrencyCode(code);
        setCounts({}); // Reset counts when changing currency
    };
    
    const handleCountChange = (label: string, count: number) => {
        setCounts(prev => ({ ...prev, [label]: count }));
    };

    const { activeCurrency, banknotes, coins, totalValue, totalCount } = useMemo(() => {
        const currency = currencies.find(c => c.code === activeCurrencyCode)!;
        
        let val = 0;
        let count = 0;
        
        const sortedDenominations = [...currency.denominations].sort((a,b) => b.value - a.value);

        sortedDenominations.forEach(d => {
            const num = counts[d.label] || 0;
            if (num > 0) {
                val += num * d.value;
                count += num;
            }
        });

        return {
            activeCurrency: currency,
            banknotes: sortedDenominations.filter(d => d.type === 'banknote'),
            coins: sortedDenominations.filter(d => d.type === 'coin'),
            totalValue: val,
            totalCount: count
        };
    }, [activeCurrencyCode, counts]);

    const handlePrint = () => {
        const getPrintContent = () => {
            const tableRows = (denominations: Denomination[]) => {
                return denominations
                    .filter(d => (counts[d.label] || 0) > 0)
                    .map(d => `
                        <tr>
                            <td>${d.label}</td>
                            <td>${counts[d.label].toLocaleString()}</td>
                            <td>${(d.value * counts[d.label]).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${activeCurrency.symbol}</td>
                        </tr>
                    `).join('');
            };
            
            const banknoteRows = tableRows(banknotes);
            const coinRows = tableRows(coins);

            const banknoteTotal = banknotes.reduce((sum, d) => sum + (counts[d.label] || 0) * d.value, 0);
            const coinTotal = coins.reduce((sum, d) => sum + (counts[d.label] || 0) * d.value, 0);

            return `
                <html>
                    <head>
                        <title>Coin Count Summary</title>
                        <style>
                            body { font-family: sans-serif; margin: 2rem; color: #000; }
                            h1, h2, h3 { color: #333; }
                            h1 { text-align: center; }
                            .summary { display: flex; justify-content: space-around; background-color: #f4f4f4; padding: 1rem; border-radius: 8px; margin-bottom: 2rem; }
                            .summary-item { text-align: center; }
                            .summary-item strong { display: block; font-size: 1rem; color: #666; margin-bottom: 0.25rem; }
                            .summary-item span { font-size: 1.8rem; font-weight: bold; color: #000; }
                            table { width: 100%; border-collapse: collapse; margin-bottom: 2rem; }
                            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                            th { background-color: #f2f2f2; }
                            td:nth-child(2), td:nth-child(3) { text-align: right; }
                            tfoot td { font-weight: bold; background-color: #f9f9f9; }
                            .print-footer { text-align: center; font-size: 0.8rem; color: #888; margin-top: 2rem; }
                        </style>
                    </head>
                    <body>
                        <h1>Coin Count Summary</h1>
                        <p class="print-footer">Date: ${new Date().toLocaleString()}</p>
                        
                        <div class="summary">
                            <div class="summary-item">
                                <strong>Total Value</strong>
                                <span>${totalValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${activeCurrency.symbol}</span>
                            </div>
                            <div class="summary-item">
                                <strong>Total Pieces</strong>
                                <span>${totalCount.toLocaleString()}</span>
                            </div>
                        </div>
                        
                        ${banknoteRows.length > 0 ? `
                            <h2>Banknotes</h2>
                            <table>
                                <thead>
                                    <tr>
                                        <th>Denomination</th>
                                        <th>Count</th>
                                        <th>Subtotal</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    ${banknoteRows}
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td colspan="2">Banknote Total</td>
                                        <td>${banknoteTotal.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${activeCurrency.symbol}</td>
                                    </tr>
                                </tfoot>
                            </table>
                        ` : ''}

                        ${coinRows.length > 0 ? `
                            <h2>Coins</h2>
                            <table>
                                <thead>
                                    <tr>
                                        <th>Denomination</th>
                                        <th>Count</th>
                                        <th>Subtotal</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    ${coinRows}
                                </tbody>
                                 <tfoot>
                                    <tr>
                                        <td colspan="2">Coin Total</td>
                                        <td>${coinTotal.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${activeCurrency.symbol}</td>
                                    </tr>
                                </tfoot>
                            </table>
                        ` : ''}
                    </body>
                </html>
            `;
        };
        
        const content = getPrintContent();

        const printWindow = window.open('', '_blank');
        if (!printWindow) {
            alert('Please allow popups to print the summary.');
            return;
        }
        printWindow.document.write(content);
        printWindow.document.close();
        printWindow.focus();
        printWindow.print();
        printWindow.close();
    };

    return html`
        <div class="coin-counter-container">
            <div class="coin-counter-header">
                <h2>${icons.coins} Coin Counter</h2>
                 <div class="header-actions">
                    <button
                        class="btn btn-secondary"
                        onClick=${handlePrint}
                        disabled=${totalCount === 0}
                        title="Print Summary"
                        style="display: flex; align-items: center; gap: 0.5rem;"
                    >
                        ${icons.print}
                        <span>Print Summary</span>
                    </button>
                    <div class="currency-selector">
                        ${currencies.map(c => html`
                            <button 
                                class=${c.code === activeCurrencyCode ? 'active' : ''}
                                onClick=${() => handleCurrencyChange(c.code)}
                            >
                                ${c.code}
                            </button>
                        `)}
                    </div>
                </div>
            </div>

            <div class="coin-counter-summary">
                <div class="summary-item">
                    <strong>Total Value</strong>
                    <span>${totalValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${activeCurrency.symbol}</span>
                </div>
                 <div class="summary-item">
                    <strong>Total Pieces</strong>
                    <span>${totalCount.toLocaleString()}</span>
                </div>
            </div>
            
            <div class="denomination-section">
                <h3>Banknotes</h3>
                <div class="denomination-grid">
                    ${banknotes.map(d => html`
                        <${DenominationCard} 
                            key=${d.label}
                            denomination=${d}
                            count=${counts[d.label]}
                            onCountChange=${handleCountChange}
                            currencySymbol=${activeCurrency.symbol}
                        />
                    `)}
                </div>
            </div>

            <div class="denomination-section">
                <h3>Coins</h3>
                <div class="denomination-grid">
                     ${coins.map(d => html`
                        <${DenominationCard} 
                            key=${d.label}
                            denomination=${d}
                            count=${counts[d.label]}
                            onCountChange=${handleCountChange}
                            currencySymbol=${activeCurrency.symbol}
                        />
                    `)}
                </div>
            </div>
        </div>
    `;
};

// frontend/src/app/pages/tools/coin-counter.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

interface Denomination { label: string; value: number; count: number; }
interface Currency { code: string; name: string; denominations: { label: string; value: number; }[]; }

const CURRENCIES: Currency[] = [
  { code: 'EUR', name: 'Euro (€)', denominations: [
    { label: '500 €', value: 500 }, { label: '200 €', value: 200 }, { label: '100 €', value: 100 }, { label: '50 €', value: 50 },
    { label: '20 €', value: 20 }, { label: '10 €', value: 10 }, { label: '5 €', value: 5 },
    { label: '2 €', value: 2 }, { label: '1 €', value: 1 }, { label: '0.50 €', value: 0.5 },
    { label: '0.20 €', value: 0.2 }, { label: '0.10 €', value: 0.1 }, { label: '0.05 €', value: 0.05 }, { label: '0.02 €', value: 0.02 }, { label: '0.01 €', value: 0.01 }
  ]},
  { code: 'CZK', name: 'Czech Koruna (Kč)', denominations: [
    { label: '5000 Kč', value: 5000 }, { label: '2000 Kč', value: 2000 }, { label: '1000 Kč', value: 1000 }, { label: '500 Kč', value: 500 },
    { label: '200 Kč', value: 200 }, { label: '100 Kč', value: 100 },
    { label: '50 Kč', value: 50 }, { label: '20 Kč', value: 20 }, { label: '10 Kč', value: 10 }, { label: '5 Kč', value: 5 },
    { label: '2 Kč', value: 2 }, { label: '1 Kč', value: 1 }
  ]},
  { code: 'USD', name: 'US Dollar ($)', denominations: [
    { label: '$100', value: 100 }, { label: '$50', value: 50 }, { label: '$20', value: 20 }, { label: '$10', value: 10 }, { label: '$5', value: 5 }, { label: '$1', value: 1 },
    { label: '$0.50', value: 0.5 }, { label: '$0.25', value: 0.25 }, { label: '$0.10', value: 0.1 }, { label: '$0.05', value: 0.05 }, { label: '$0.01', value: 0.01 }
  ]}
];

@Component({
  selector: 'app-coin-counter',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="page-header">
      <h1>Coin Counter</h1>
      <div class="header-actions">
        <select [(ngModel)]="selectedCurrency" (ngModelChange)="onCurrencyChange()" class="currency-select">
          @for (c of currencies; track c.code) { <option [ngValue]="c">{{ c.name }}</option> }
        </select>
        <button class="btn" (click)="reset()">Reset</button>
        <button class="btn btn-primary" (click)="print()">🖨 Print</button>
      </div>
    </div>
    <div class="denom-grid">
      @for (d of denominations; track d.label) {
        <div class="denom-card" [class.has-value]="d.count > 0">
          <div class="denom-label">{{ d.label }}</div>
          <div class="denom-input-row">
            <button class="btn-sm" (click)="d.count = Math.max(0, d.count - 1)">−</button>
            <input type="number" [(ngModel)]="d.count" min="0" class="denom-input">
            <button class="btn-sm" (click)="d.count = d.count + 1">+</button>
          </div>
          <div class="denom-subtotal">{{ (d.value * d.count) | number:'1.2-2' }} {{ selectedCurrency.code }}</div>
        </div>
      }
    </div>
    <div class="total-bar">
      <span class="total-label">Total:</span>
      <span class="total-value">{{ total | number:'1.2-2' }} {{ selectedCurrency.code }}</span>
      <span class="total-pieces">({{ totalPieces }} pieces)</span>
    </div>
  `,
  styles: [`
    .page-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px; flex-wrap: wrap; gap: 12px; }
    .page-header h1 { margin: 0; font-size: 24px; font-weight: 700; }
    .header-actions { display: flex; gap: 8px; align-items: center; }
    .currency-select { padding: 8px 12px; border: 1px solid var(--border-color,#ddd); border-radius: 8px; font-size: 14px; background: var(--bg-card,#fff); color: var(--text-primary,#333); }
    .btn { padding: 8px 16px; border: 1px solid var(--border-color,#ddd); border-radius: 8px; cursor: pointer; font-size: 14px; background: var(--bg-card,#fff); color: var(--text-primary,#333); }
    .btn-primary { background: #3498db; color: #fff; border-color: #3498db; }
    .denom-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr)); gap: 12px; margin-bottom: 20px; }
    .denom-card { background: var(--bg-card,#fff); border: 1px solid var(--border-color,#e5e7eb); border-radius: 12px; padding: 16px; text-align: center; transition: all 0.2s; }
    .denom-card.has-value { border-color: #3498db; background: var(--bg-highlight,#ebf5ff); }
    .denom-label { font-size: 18px; font-weight: 700; margin-bottom: 8px; color: var(--text-primary,#333); }
    .denom-input-row { display: flex; align-items: center; gap: 6px; justify-content: center; margin-bottom: 8px; }
    .btn-sm { width: 28px; height: 28px; border-radius: 50%; border: 1px solid var(--border-color,#ddd); background: var(--bg-secondary,#f8f9fa); cursor: pointer; font-size: 16px; display: flex; align-items: center; justify-content: center; color: var(--text-primary,#333); }
    .denom-input { width: 60px; text-align: center; padding: 6px 4px; border: 1px solid var(--border-color,#ddd); border-radius: 8px; font-size: 16px; font-weight: 600; background: var(--bg-input,#fff); color: var(--text-primary,#333); }
    .denom-input::-webkit-inner-spin-button, .denom-input::-webkit-outer-spin-button { -webkit-appearance: none; }
    .denom-input { -moz-appearance: textfield; }
    .denom-subtotal { font-size: 13px; color: var(--text-secondary,#666); font-weight: 500; }
    .total-bar { background: var(--bg-card,#fff); border: 2px solid #3498db; border-radius: 12px; padding: 20px 24px; display: flex; align-items: center; gap: 12px; }
    .total-label { font-size: 18px; font-weight: 700; color: var(--text-primary,#333); }
    .total-value { font-size: 28px; font-weight: 800; color: #3498db; }
    .total-pieces { font-size: 14px; color: var(--text-secondary,#666); }
  `]
})
export class CoinCounterComponent {
  Math = Math;
  currencies = CURRENCIES;
  selectedCurrency = CURRENCIES[0];
  denominations: Denomination[] = [];

  constructor() { this.onCurrencyChange(); }

  onCurrencyChange() {
    this.denominations = this.selectedCurrency.denominations.map(d => ({ ...d, count: 0 }));
  }

  get total() { return this.denominations.reduce((s, d) => s + d.value * d.count, 0); }
  get totalPieces() { return this.denominations.reduce((s, d) => s + d.count, 0); }
  reset() { this.denominations.forEach(d => d.count = 0); }

  print() {
    const items = this.denominations.filter(d => d.count > 0);
    const w = window.open('', '_blank');
    if (!w) return;
    const rows = items.map(d => `<tr><td>${d.label}</td><td style="text-align:center">${d.count}</td><td style="text-align:right">${(d.value * d.count).toFixed(2)} ${this.selectedCurrency.code}</td></tr>`).join('');
    w.document.write(`<!DOCTYPE html><html><head><title>Coin Count</title><style>body{font-family:sans-serif;padding:20px}table{width:100%;border-collapse:collapse}th,td{padding:8px 12px;border-bottom:1px solid #ddd;text-align:left}th{font-weight:bold}.total{font-size:20px;font-weight:bold;margin-top:16px}</style></head><body><h2>Coin Count - ${this.selectedCurrency.name}</h2><table><thead><tr><th>Denomination</th><th style="text-align:center">Count</th><th style="text-align:right">Subtotal</th></tr></thead><tbody>${rows}</tbody></table><p class="total">Total: ${this.total.toFixed(2)} ${this.selectedCurrency.code} (${this.totalPieces} pcs)</p><script>window.print()</script></body></html>`);
    w.document.close();
  }
}
